<?xml version="1.0" encoding="utf-8"?><Database Name="ApcursDb" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ApcursDb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ApcursDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArticleText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LikeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShortTitle" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ArticlePicture" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Article_ArticleComment" Member="ArticleComments" ThisKey="id" OtherKey="Articleid" Type="ArticleComment" />
      <Association Name="Article_ArticleTag" Member="ArticleTags" ThisKey="id" OtherKey="ArticleId" Type="ArticleTag" />
      <Association Name="User_Article" Member="User" ThisKey="Userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArticleComment" Member="ArticleComments">
    <Type Name="ArticleComment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentText" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Articleid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Article_ArticleComment" Member="Article" ThisKey="Articleid" OtherKey="id" Type="Article" IsForeignKey="true" />
      <Association Name="User_ArticleComment" Member="User" ThisKey="Userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArticleTag" Member="ArticleTags">
    <Type Name="ArticleTag">
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Article_ArticleTag" Member="Article" ThisKey="ArticleId" OtherKey="id" Type="Article" IsForeignKey="true" />
      <Association Name="Tag_ArticleTag" Member="Tag" ThisKey="TagId" OtherKey="id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blog" Member="Blogs">
    <Type Name="Blog">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlogText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LikeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShortTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BlogPicture" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="User_Blog" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ShortTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FromUserid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToUserid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="User" ThisKey="FromUserid" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="User1" ThisKey="ToUserid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionTag" Member="QuestionTags">
    <Type Name="QuestionTag">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Question_QuestionTag" Member="Question" ThisKey="QuestionId" OtherKey="id" Type="Question" IsForeignKey="true" />
      <Association Name="Tag_QuestionTag" Member="Tag" ThisKey="TagId" OtherKey="id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubAnswer" Member="SubAnswers">
    <Type Name="SubAnswer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_SubAnswer" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="Answer_SubAnswer" Member="Answer" ThisKey="AnswerId" OtherKey="id" Type="Answer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="About" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Reputation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfilPicture" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConfirmedEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NameSurname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Badge" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Job" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Twitter" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Github" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Linkedin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Blog" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="User_Article" Member="Articles" ThisKey="id" OtherKey="Userid" Type="Article" />
      <Association Name="User_ArticleComment" Member="ArticleComments" ThisKey="id" OtherKey="Userid" Type="ArticleComment" />
      <Association Name="User_Blog" Member="Blogs" ThisKey="id" OtherKey="UserId" Type="Blog" />
      <Association Name="User_Message" Member="Messages" ThisKey="id" OtherKey="FromUserid" Type="Message" />
      <Association Name="User_Message1" Member="Messages1" ThisKey="id" OtherKey="ToUserid" Type="Message" />
      <Association Name="User_SubAnswer" Member="SubAnswers" ThisKey="id" OtherKey="UserId" Type="SubAnswer" />
      <Association Name="User_MyFavourite" Member="MyFavourites" ThisKey="id" OtherKey="UserId" Type="MyFavourite" />
      <Association Name="User_Question" Member="Questions" ThisKey="id" OtherKey="Userid" Type="Question" />
      <Association Name="User_VotedQuestion" Member="VotedQuestions" ThisKey="id" OtherKey="UserId" Type="VotedQuestion" />
      <Association Name="User_Answer" Member="Answers" ThisKey="id" OtherKey="Userid" Type="Answer" />
      <Association Name="User_VotedAnswer" Member="VotedAnswers" ThisKey="id" OtherKey="UserId" Type="VotedAnswer" />
      <Association Name="User_Discussion" Member="Discussions" ThisKey="id" OtherKey="UserId" Type="Discussion" />
      <Association Name="User_SubDiscussion" Member="SubDiscussions" ThisKey="id" OtherKey="UserId" Type="SubDiscussion" />
    </Type>
  </Table>
  <Table Name="dbo.MyFavourites" Member="MyFavourites">
    <Type Name="MyFavourite">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_MyFavourite" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="Question_MyFavourite" Member="Question" ThisKey="QuestionId" OtherKey="id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsReply" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShortTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FavoriCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_QuestionTag" Member="QuestionTags" ThisKey="id" OtherKey="QuestionId" Type="QuestionTag" />
      <Association Name="Question_MyFavourite" Member="MyFavourites" ThisKey="id" OtherKey="QuestionId" Type="MyFavourite" />
      <Association Name="Question_VotedQuestion" Member="VotedQuestions" ThisKey="id" OtherKey="QuestionId" Type="VotedQuestion" />
      <Association Name="Question_Answer" Member="Answers" ThisKey="id" OtherKey="Questionid" Type="Answer" />
      <Association Name="User_Question" Member="User" ThisKey="Userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VotedQuestions" Member="VotedQuestions">
    <Type Name="VotedQuestion">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LikeorDislike" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Question_VotedQuestion" Member="Question" ThisKey="QuestionId" OtherKey="id" Type="Question" IsForeignKey="true" />
      <Association Name="User_VotedQuestion" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Answer" Member="Answers">
    <Type Name="Answer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Questionid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSolved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Answer_SubAnswer" Member="SubAnswers" ThisKey="id" OtherKey="AnswerId" Type="SubAnswer" />
      <Association Name="Answer_VotedAnswer" Member="VotedAnswers" ThisKey="id" OtherKey="AnswerId" Type="VotedAnswer" />
      <Association Name="Question_Answer" Member="Question" ThisKey="Questionid" OtherKey="id" Type="Question" IsForeignKey="true" />
      <Association Name="User_Answer" Member="User" ThisKey="Userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VotedAnswers" Member="VotedAnswers">
    <Type Name="VotedAnswer">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LikeorDislike" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Answer_VotedAnswer" Member="Answer" ThisKey="AnswerId" OtherKey="id" Type="Answer" IsForeignKey="true" />
      <Association Name="User_VotedAnswer" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Discussions" Member="Discussions">
    <Type Name="Discussion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShortTitle" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="DiscussionText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsWantEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Discussion_SubDiscussion" Member="SubDiscussions" ThisKey="id" OtherKey="DiscussionId" Type="SubDiscussion" />
      <Association Name="User_Discussion" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArticleNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tag_ArticleTag" Member="ArticleTags" ThisKey="id" OtherKey="TagId" Type="ArticleTag" />
      <Association Name="Tag_QuestionTag" Member="QuestionTags" ThisKey="id" OtherKey="TagId" Type="QuestionTag" />
    </Type>
  </Table>
  <Table Name="dbo.SubDiscussions" Member="SubDiscussions">
    <Type Name="SubDiscussion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiscussionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Discussion_SubDiscussion" Member="Discussion" ThisKey="DiscussionId" OtherKey="id" Type="Discussion" IsForeignKey="true" />
      <Association Name="User_SubDiscussion" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>